### ISSUE TITLE
Xcode quit unexpectedly while using the IconMaker plug-in.

### ISSUE THREAD

**Issue by Lao-Ben** [kaphacius/IconMaker#1]
I got this error message on Xcode 6.3.2 after updating Alcatraz to 1.1.3.
How can I disable the plugin so I can start Xcode?

**Comment by kaphacius** [comment]
i will look into that asap

**Comment by kaphacius** [comment]
to delete the plugin (and stop crashing), go to ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins

**Comment by kaphacius** [comment]
fixed!
