### ISSUE TITLE
Support for SVG (PDF)

### ISSUE THREAD

**Issue by mingsai** [kaphacius/IconMaker#12]
Xcode supports SVG files saved out from Adobe illustrator as pdf file. SVG files can often be 100x100 px since they are scalable without loss of quality. Can you adapt the current plugin to support these files?

**Comment by kaphacius** [comment]
I'll look into that!
thanks for the idea

**Comment by kaphacius** [comment]
@mingsai I thought about this for a bit. What are we trying to achieve? 
Multiple SVG files? Doesn't really make sense, since it can be scaled w/o loss of quality
Or generate multiple PNGs from one SVG?
