### ISSUE TITLE
IconMaker in Xcode 8 Source Editor extensions

### ISSUE THREAD

**Issue by litt1e-p** [kaphacius/IconMaker#15]
@kaphacius , hi, IconMaker is pretty great, but donot work in Xcode 8. is it possible build a `Source Editor extensions` for Xcode 8 or other version in future?

**Comment by kaphacius** [comment]
@litt1e-p hey! currently there is a workaround to make plugins work in Xcode8, you can read about it [here](https://github.com/fpg1503/MakeXcodeGr8Again)
Regarding `Source Editor extensions`, that is not currently possible, because they only work with the source editor in Xcode
