### ISSUE TITLE
MenuItem not showing in Xcode 8

### ISSUE THREAD

**Issue by lanza** [kaphacius/IconMaker#16]
There's simply no menu option upon right clicking on an image asset in Xcode 8. Uninstalled and reinstalled a few times. Not showing up. I used XVim's unhinging process and all my other plugins work as expected.

**Comment by BrightBeacon** [comment]
maybe:
find ~/Library/Application\ Support/Developer/Shared/Xcode/Plug-ins -name Info.plist -maxdepth 3 | xargs -I{} defaults write {} DVTPlugInCompatibilityUUIDs -array-add `defaults read /Applications/Xcode.app/Contents/Info DVTPlugInCompatibilityUUID`

by http://www.jianshu.com/p/dc2fc2a680fc
