### ISSUE TITLE
IconMaker not working on Xcode 6.3.2

### ISSUE THREAD

**Issue by ricardobed** [kaphacius/IconMaker#2]
Installed the plugin using Alcatraz 1.1.5 and nothing happens. I tried adding the UUID E969541F-E6F9-4D25-8158-72DC3545A6C6 to the info.plist and Xcode crashes at launch.

**Comment by kaphacius** [comment]
i will look into it ASAP

**Comment by kaphacius** [comment]
to delete the plugin (and stop crashing), go to ~/Library/Application Support/Developer/Shared/Xcode/Plug-ins

**Comment by ricardobed** [comment]
Yeah, I know how to delete it and don't really need to delete it unless I add the UUID that makes it crash. Hope you can fix this soon. I really love this plugin.

**Comment by kaphacius** [comment]
sorry, will do as soon as i can. a bit busy with the new job :)

**Comment by kaphacius** [comment]
fixed!

**Comment by kaphacius** [comment]
fixed!
