### ISSUE TITLE
IconMaker fails after selecting file

### ISSUE THREAD

**Issue by albertbori** [kaphacius/IconMaker#3]
Following the same steps as highlighted in the gif in the readme:
1. Create a new App Icon into my Images.xcassets within Xcode
2. Select the new App Icon in the xcassets navigator view in Xcode
3. Select Edit -> Make an app icon
4. Select a 1024x1024 png file

Expected results:
The plugin should create all the icon sizes and add them to that app icon image set

Actual results:
I get the following pop-up error: 

> The operation couldn't be completed.
> (Something went wrong :( error 0.)

The app icon image sets are still empty.

Environment: OSX 10.10.4 | Xcode 6.4 (6E35b)

**Comment by kaphacius** [comment]
will look into this ASAP

**Comment by kaphacius** [comment]
i can't repro it. can you provide the project/icon that fails?

**Comment by albertbori** [comment]
Unfortunately I am not able to share that information. Are there any logs I can send you? If so, where should I look for them?

**Comment by kaphacius** [comment]
not really, no logs.
did you try moving the icon in some other directory? i think the pathing may be an issue

**Comment by albertbori** [comment]
The path to the Images.xcassets was the issue. (I had it in a subdirectory. After moving it to the root directory, it worked.) Is there a way for the plugin to detect the location of the open .xcassets file that you are working with?

**Comment by kaphacius** [comment]
i thought about that. i could recursively search all the folders, but then I can't really determine which xcassets should I use, because there can be more than one target

**Comment by albertbori** [comment]
Yup. At least for now, you could add some info to the readme.md that outlines the prerequisites:
- Assets file must be named 'Images.xcassets'
- Assets file must be located in project root
- AppIcon asset must be named 'AppIcon'

**Comment by kaphacius** [comment]
that's actually an awesome idea! thank you for that :)

**Comment by kaphacius** [comment]
Done
