### ISSUE TITLE
Add support for WatchKit apps

### ISSUE THREAD

**Issue by hipwelljo** [kaphacius/IconMaker#4]
It would be really great if this would detect which asset catalog you have selected, either one inside the app or inside a WatchKit extension, and generate the sizes appropriate for that catalog. It's a pain to generate the sizes for Apple Watch, though not quite as painful as the iOS App Icon.

**Comment by kaphacius** [comment]
i will look into it, thanks for suggestion

**Comment by kaphacius** [comment]
Done
