### ISSUE TITLE
Not installing in Xcode 7 beta 5

### ISSUE THREAD

**Issue by pranav18** [kaphacius/IconMaker#7]
Hello,
First of all its my fav plugin of Xcode.
But its not working when I upgrade it to Xcode 7 Beta 5.
Please resolve this issue.

**Comment by kaphacius** [comment]
Released version 2.0, now works on Xcode 7.0

**Comment by pranav18** [comment]
I am getting this issue when I am running project.
File Name : IconMaker.swift
![screen shot 2015-09-17 at 4 20 15 pm](https://cloud.githubusercontent.com/assets/10543748/9931303/67fb88a4-5cef-11e5-8507-b172299279cb.png)

And some thing went wrong with alcatraz. its not installing the plugins

**Comment by kaphacius** [comment]
it works on my Xcode 7.0 GM
please try updating your Xcode :)

**Comment by pranav18** [comment]
Thank you my friend.
its working :)
