### ISSUE TITLE
not show in xcode 7.1 (7B91b)

### ISSUE THREAD

**Issue by iKazakov** [kaphacius/IconMaker#9]
![assets xcassets 2015-10-26 13-23-07](https://cloud.githubusercontent.com/assets/14798617/10723430/8c46dfea-7bdc-11e5-93be-a368b8b76e74.png)

**Comment by kaphacius** [comment]
that's really strange. can you try reinstalling it and restarting Xcode? also, are you clicking on an app icon? i can't tell that from the screenshot.
it works fine for me, I just checked
